name: Common Test

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: circleci/postgres:11.3-alpine-ram
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: opentelemetry_ecto_test

    steps:
    - uses: actions/checkout@v1.0.0
    - uses: erlef/setup-elixir@v1
      with:
        otp-version: '22.x'
        elixir-version: '1.9.x'
    - name: Fetch deps
      run: mix deps.get
    - name: Run tests
      run: mix test
